# Generated by Django 5.0.1 on 2024-12-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_espacio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='bloques_seleccionados',
            field=models.JSONField(default=list),
        ),
    ]
